local constants = require('lolloArrivalsDeparturesPredictor.constants')

-- LOLLO NOTE from UG on regex
-- Hi. This is what we do with the expr and replace if the label is set to custom filter:
--[[
    std::regex_replace(
        text,
        std::regex(expr),
        replace,
        std::regex_constants::format_sed | std::regex_constants::format_no_copy
    );
]]
-- with the 4th parameter "flags", we set the format to the "Sed" format
-- it is possible that the C++ implementation does not support the full regexp capabilities
-- aside from that we do not do anything special with the input strings

--[[
    https://www.cplusplus.com/reference/regex/regex_replace/
    https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html#tag_20_116_13_03
    https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=net-6.0
    https://www.cplusplus.com/reference/regex/regex_constants/
]]

-- for platform panels, stick this in the model editor under "options - config - name"
-- local _testText = "@_track_@88@_1_@Stazione di Genova Brignole@_2_@IC 999IC 999IC 999@_3_@22:25@_4_@Ü Bigottu@_5_@REG 11198-REG 11198@_6_@1:11@_clock_@01:12:20@"
-- for station panels, stick this in the model editor under "options - config - name"
-- local _testText = "@_header_@Departures@_footer_@VeryVeryVeryLongLongLongTextTextText@_1_@To@_2_@@_3_@Platform@_4_@TimeLong@_5_@Stazione Di Genova Brignole@_6_@IC335IC335@_7_@2@_8_@1:50@_9_@Torino Porta Nuova Molto molto molto lungo@_10_@REG 1157999 with restaurant@_11_@21@_12_@19:42@_13_@Sestri Levante@_14_@TEE 34@_15_@12@_16_@19:48@_17_@Milano Centrale@_18_@REG 11194@_19_@24@_20_@19:59@_21_@Milano Centrale@_22_@REG 98989@_23_@24@_24_@20:59@_25_@Milano Centrale@_26_@IC 942@_27_@24@_28_@21:59@_29_@Venezia Santa Lucia@_30_@IC 777@_32_@24@_32_@22:59@_33_@Ventimiglia - Marseille@_34_@IC 888@_35_@24@_36_@23:59@_clock_@01:12:20@"

local function getRegexParams(counter)
    return {
        -- text = "@1SELECT_PART_1@2SELECT_PART_2@",
        -- text = "@1SEL_P1@2SEL_P2@31:50@4Brignole@52@61:50@7Porta Nuova@824@923:59@",
        -- expr = "@2([a-zA-Z0-9_]+)@", -- works
        -- expr = "@1([a-zA-Z0-9_]+)@", -- works
        -- expr = "@1([^@]+)@", -- works best
        -- expr = "@" .. counter .. "([^@]+)@",
        expr = "@_" .. counter .. "_@([^@]+)@",
        replace="\\1", -- works
    }
end
-- LOLLO insert the line names where there is space, typically to the right of the destination in the wide panel
-- and in place of the track number in the street platform panel.
-- I doubt they fit in the narrow station panel.
-- The train track platform panel probably has a bit of space.
local utils = {
    -- LOLLO NOTE if a construction contains models without bounding info and collider,
    -- it will still detect collisions with them. With these, we avoid that problem.
    getVoidBoundingInfo = function()
        return {} -- this seems the same as the following
        -- return {
        --     bbMax = { 0, 0, 0 },
        --     bbMin = { 0, 0, 0 },
        -- }
    end,
    getVoidCollider = function()
        -- return {
        --     params = {
        --         halfExtents = { 0, 0, 0, },
        --     },
        --     transf = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, },
        --     type = 'BOX',
        -- }
        return {
            type = 'NONE'
        }
    end,
}

    utils.getPlatformDisplayLabelList = function()
        local _zed0 = 2.67
        local _dZed = -0.1
        local function zed(counter) -- 3 items per row
            return _zed0 + math.floor((counter - 1) / 3) * _dZed
        end

        local _size1 = {7.2, 1}
        local _size2 = {3.0, 0.667}
        local _size3 = {3, 1}
        local _yShiftA = -0.12
        local _yShiftB = 0.12

        return {
            labels = {
                -- face A
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.track),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.00, _yShiftA, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.00, _yShiftA, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- face B
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.track),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = {4, 1},
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.65, _yShiftB, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.805, _yShiftB, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.805, _yShiftB, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
            },
        }
    end
    utils.getStreetPlatformDisplayLabelList = function()
        -- for now, these are the same as the train displays,
        -- except they have no track number.
        -- This can be set in the construction configs,
        -- without making a dedicated model.
        local _zed0 = 2.67
        local _dZed = -0.1
        local function zed(counter) -- 3 items per row
            return _zed0 + math.floor((counter - 1) / 3) * _dZed
        end

        local _size1 = {7.2, 1}
        local _size2 = {3.0, 0.667}
        local _size3 = {3, 1}
        local _yShiftA = -0.12
        local _yShiftB = 0.12

        return {
            labels = {
                -- face A
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.00, _yShiftA, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  0.26, _yShiftA, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.00, _yShiftA, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, -1, 0, 0,  1.24, _yShiftA, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- face B
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    size = {4, 1},
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.65, _yShiftB, 2.8, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.805, _yShiftB, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  1.54, _yShiftB, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.805, _yShiftB, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.541, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { -0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.55, _yShiftB, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
            },
        }
    end
    utils.getStationDisplayLabelList = function()
        local _zed0 = 3.65
        local _dZed = -0.1
        local function zed(counter) -- 4 items per row
            return _zed0 + math.floor((counter - 1) / 4) * _dZed
        end

        local _sizeLeft = {6.4, 1}
        local _sizeMid = {3, 1}
        local _sizeRight = { 3, 1, }

        return {
            labels = {
                -- {
                -- 	alignment = "LEFT",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM", -- 'NONE', 'NUMBER', 'CUSTOM'
                -- 	-- filter = 'NONE',
                -- 	fitting = "SCALE",
                -- 	font = 'Lato', -- 'Lato', 'Noto'
                -- 	nLines = 2,
                -- 	params = {
                -- 		-- expr = '/[a-zA-Z]+/gm',
                -- 		-- expr = '/[A-S]+/gm',
                -- 		-- expr = '[A-S]',
                -- 		expr = "([a-zA-Z-]*)",
                -- 		-- replace = 'KOK\\0MNM\\1 UNO\\2DUE',
                -- 		-- replace = 'KOK',
                -- 		replace = '\\0',
                -- 	},
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1, 1, },
                -- 	transf = { 1, 0, 0, 0,
                -- 		0, 0, 1, 0,
                -- 		0, -1, 0, 0,
                -- 		-0.5, -0.07, 4.0, 1,
                -- 	},
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.header),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    -- size = { 1.02, 0.15, },
                    size = {4, 1},
                    -- transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.12, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(7),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(7), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(8),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(8), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(9),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(9), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(11),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(11), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(12),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(12), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(13),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(13), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(15),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(15), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(16),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(16), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(17),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(17), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(19),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(19), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(20),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(20), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(21),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(21), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(23),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(23), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(24),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(24), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(25),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(25), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(27),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(27), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(28),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(28), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(29),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(29), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(31),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(31), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(32),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(32), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(33),
                    renderMode = "EMISSIVE",
                    size = _sizeLeft,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.55, -0.06, zed(33), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(35),
                    renderMode = "EMISSIVE",
                    size = _sizeMid,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  -0.05, -0.06, zed(35), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(36),
                    renderMode = "EMISSIVE",
                    size = _sizeRight,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.25, -0.06, zed(36), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- {
                -- 	alignment = "CENTER",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM",
                -- 	fitting = "CUT",
                -- 	nLines = 1,
                -- 	params = getRegexParams(constants.nameTags.clock),
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1.02, 0.15, },
                -- 	transf = { 1, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                	alignment = "CENTER",
                	alpha = 1,
                	alphaMode = "CUTOUT",
                	childId = "",
                	-- color = { 1, 1, 1, },
                    color = { 1, 0.54, 0, },
                	-- filter = "CUSTOM",
                    filter = "NONE",
                	fitting = "CUT",
                	nLines = 2,
                	-- params = getRegexParams(constants.nameTags.footer),
                	renderMode = "EMISSIVE",
                	size = {5.5, 1},
                    transf = { 0.2, 0, 0, 0,  0, 0, 0.2, 0,  0, 1, 0, 0,  -0.55, -0.06, 2.6, 1, },
                	-- type = "NAME",
                    type = "COMPANY_NAME",
                	verticalAlignment = "CENTER",
                },
            },
        }
    end
    utils.getStationWideDisplayLabelList = function()
        local _zed0 = 3.65
        local _dZed = -0.1
        local function zed(counter) -- 4 items per row
            return _zed0 + math.floor((counter - 1) / 4) * _dZed
        end

        local _size1 = {11, 1}
        local _size2 = {4.5, 0.667}
        local _size3 = {3, 1}
        local _size4 = { 3, 1, }
        local _x1 = -1.02
        local _x2 = 0.1
        local _x3 = 0.38
        local _x4 = 0.72
    
        return {
            labels = {
                -- {
                -- 	alignment = "LEFT",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM", -- 'NONE', 'NUMBER', 'CUSTOM'
                -- 	-- filter = 'NONE',
                -- 	fitting = "SCALE",
                -- 	font = 'Lato', -- 'Lato', 'Noto'
                -- 	nLines = 2,
                -- 	params = {
                -- 		-- expr = '/[a-zA-Z]+/gm',
                -- 		-- expr = '/[A-S]+/gm',
                -- 		-- expr = '[A-S]',
                -- 		expr = "([a-zA-Z-]*)",
                -- 		-- replace = 'KOK\\0MNM\\1 UNO\\2DUE',
                -- 		-- replace = 'KOK',
                -- 		replace = '\\0',
                -- 	},
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1, 1, },
                -- 	transf = { 1, 0, 0, 0,
                -- 		0, 0, 1, 0,
                -- 		0, -1, 0, 0,
                -- 		-0.5, -0.07, 4.0, 1,
                -- 	},
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.header),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(constants.nameTags.clock),
                    renderMode = "EMISSIVE",
                    -- size = { 1.02, 0.15, },
                    size = {4, 1},
                    -- transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  0.6, -0.06, 3.83, 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(1),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(1), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(2),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(2), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(3),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(3), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 1, 1, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(4),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(4), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(5),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(5), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(6),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(6), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(7),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(7), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(8),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(8), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(9),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(9), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(10),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(10), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(11),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(11), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(12),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(12), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(13),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(13), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(14),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(14), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(15),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(15), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(16),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(16), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(17),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(17), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(18),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(18), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(19),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(19), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(20),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(20), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(21),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(21), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(22),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(22), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(23),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(23), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(24),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(24), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(25),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(25), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(26),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(26), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(27),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(27), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(28),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(28), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(29),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(29), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(30),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(30), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(31),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(31), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(32),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(32), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(33),
                    renderMode = "EMISSIVE",
                    size = _size1,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x1, -0.06, zed(33), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "LEFT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(34),
                    renderMode = "EMISSIVE",
                    size = _size2,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x2, -0.06, zed(34), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(35),
                    renderMode = "EMISSIVE",
                    size = _size3,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x3, -0.06, zed(35), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                {
                    alignment = "RIGHT",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    color = { 1, 0.54, 0, },
                    filter = "CUSTOM",
                    fitting = "CUT",
                    nLines = 1,
                    params = getRegexParams(36),
                    renderMode = "EMISSIVE",
                    size = _size4,
                    transf = { 0.1, 0, 0, 0,  0, 0, 0.1, 0,  0, 1, 0, 0,  _x4, -0.06, zed(36), 1, },
                    type = "NAME",
                    verticalAlignment = "CENTER",
                },
                -- {
                -- 	alignment = "CENTER",
                -- 	alpha = 1,
                -- 	alphaMode = "CUTOUT",
                -- 	childId = "",
                -- 	color = { 1, 1, 1, },
                -- 	filter = "CUSTOM",
                -- 	fitting = "CUT",
                -- 	nLines = 1,
                -- 	params = getRegexParams(constants.nameTags.clock),
                -- 	renderMode = "EMISSIVE",
                -- 	size = { 1.02, 0.15, },
                -- 	transf = { 1, 0, -0, 0, 0, 0, 1, 0, 0, -1, 0, 0, -0.5, -0.07, 2.6, 1, },
                -- 	type = "NAME",
                -- 	verticalAlignment = "CENTER",
                -- },
                {
                    alignment = "CENTER",
                    alpha = 1,
                    alphaMode = "CUTOUT",
                    childId = "",
                    -- color = { 1, 1, 1, },
                    color = { 1, 0.54, 0, },
                    -- filter = "CUSTOM",
                    filter = "NONE",
                    fitting = "CUT",
                    nLines = 2,
                    -- params = getRegexParams(constants.nameTags.footer),
                    renderMode = "EMISSIVE",
                    size = {10, 1},
                    transf = { 0.2, 0, 0, 0,  0, 0, 0.2, 0,  0, 1, 0, 0,  -1.01, -0.06, 2.6, 1, },
                    -- type = "NAME",
                    type = "COMPANY_NAME",
                    verticalAlignment = "CENTER",
                },
            },
        }
    end

return utils
